on:
  push:
  pull_request:

name: check

jobs:
  check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2

      - name: Install Codecov
        run: sudo pip install codecov

      - name: qmake
        run: qmake

      - name: make
        run: make --silent

      - name: run
        run: ./travis_qmake_gcc_cpp14_gcov

      - name: Measure codecov
        run: |
          ./get_code_cov.sh >/dev/null
          codecov >/dev/null
          bash <(curl -s https://codecov.io/bash)

